pub(crate) mod bitmap;
pub(crate) mod part;
mod placed_part;
mod placement;
pub(crate) mod placer;
pub(crate) mod plate;
pub(crate) mod plate_shape;
pub(crate) mod point;
pub mod rectangle;
pub(crate) mod request;
pub(crate) mod solution;
pub(crate) mod util;
